name: Update Slides, PDFs, HTMLs
on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
      - 'img/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r 'requirements.txt'

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Install Latex
        run: sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Make all
        run: |
          cd ./notebooks
          make all

      - name: Commit changes
        run: |
          git config --global user.name 'BuilderBot'
          git config --global user.email 'BuilderBot@users.noreply.github.com'
          git commit -am "Update Slides, PDFs, and HTMLs with latest changes."
          git push
